### ISSUE TITLE
Why use another UX implementation of editing row?

### ISSUE THREAD

**Issue by IniterWorker** [Domino987/material-table-formik#3]
Hello,

I'm wondering why your current implementation uses a dialogue box. Is it about a personal choice or about some limitations? 

> This will display the edit/update/delete action in a separate dialogue instead of inline.

Best regards,

**Comment by Domino987** [comment]
Hi,
I needed validation so I started to extend the table. During that, I got questions if a dialog is possible, so I added a dialog. So it's more personal choice.
