### ISSUE TITLE
updating your edit 

### ISSUE THREAD

**Issue by eebbann** [Domino987/material-table-formik#32]
how do you save/update row after editing it please assist using your example here
https://codesandbox.io/s/ty094?file=/src/index.js

**Comment by Domino987** [comment]
What did you try, what do you want to achieve exactly? Can you be more specific instead of just demanding help?

**Comment by eebbann** [comment]
apologise for how i made the comment ... had to re-read.. so basically i am trying to update my table sir by using your implementation (material-table formik) the main idea is to use dialog box to update and save the  updated row when done as i noticed with the example u gave when i edit it doent save and im new to material-table ..if you can please asist on how i can save
when i update

**Comment by Domino987** [comment]
https://codesandbox.io/s/material-table-selection-different-data-from-table-forked-nr67kx?file=/src/index.js This works, but it probably won't for your setup because yours will be different.

**Comment by eebbann** [comment]
thank you so much ..i should be able to work with this

**Comment by Domino987** [comment]
Ok perfect
