### ISSUE TITLE
Setting a Cell as non Editable

### ISSUE THREAD

**Issue by mikeKorakakis** [Domino987/material-table-formik#7]
Hello,

Is there a way to set a cell as non editable.
I am currently adding the attribute { editable: "never" } to some cells but it does not seem to have any effect.
Is this functionality excluded from the library or am i missing something?

Best regards,

**Comment by Domino987** [comment]
It is not yet implemented. I will do that tomorrow.

**Comment by Domino987** [comment]
Fixed with the newest release.
