### ISSUE TITLE
Showing validation messages on dropdown lists using yup

### ISSUE THREAD

**Issue by mikeKorakakis** [Domino987/material-table-formik#8]
Hello,

I am trying validate the add/update form using yup and validationSchema property.
When i create a dropdown list using the lookup field type and the form is invalid 
although it doesn't submit, it does not display any error message at all.
Is this a limitation of formik? 

Best regards,

**Comment by Domino987** [comment]
Hi,
seems like that's not supported yet. But with the new version of MT with validation, I wanted to rewrite it a bit to support that as well.

**Comment by Domino987** [comment]
Supported with next release
