### ISSUE TITLE
[Improvement] Hide fields that are non editable when adding or editing.

### ISSUE THREAD

**Issue by mikeKorakakis** [Domino987/material-table-formik#9]
Hello,
When adding or editing a non editable field there is no input area but the labels are still shown.
I can hide them using css but the empty space is still shown.
I could also hide the parent divs using the cssv4 :has attribute but it is not yet supported by most browsers.
Is there a way to implement a feature so that the labels are not shown?
Maybe an extra css class could be added.

Best Regards,

**Comment by Domino987** [comment]
I will change it so it respects the hidden feature.

**Comment by Domino987** [comment]
Will be fixed with next release.
